### ISSUE TITLE
The plugin does not work on the device (IPhone 6 / IOS10)

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-camera#10]
I have the same application running on emulator and the device, and the photo library is not opening on the device (I do the same on the emulator and it does open).

It does show a message in the console:
"NativeScript loaded bundle file:///System/Library/Frameworks/Photos.framework"
but nothing happens.

I noticed it happens even if you just request the permissions, the application just hangs at the call

**Comment by ignaciolarranaga** [comment]
I noticed also that when I opened the CamaraTest app at the device and the emulator (same OS = iOS 10 / same Phone = IPhone6) it does different things, here are the 2 screenshots, in 1 case it opens the photo library, in the other, it does open the camera app.

Real device:
![real_phone_screenshot](https://cloud.githubusercontent.com/assets/15932965/19618182/77f99e38-9819-11e6-8c1a-34a1cd3a7472.jpg)

Emulator:
![emulator_screenshot](https://cloud.githubusercontent.com/assets/15932965/19618195/b3e016c0-9819-11e6-8346-619a2cca2baa.jpg)

**Comment by nsndeck** [comment]
Hi @ignaciolarranaga,

I've tried to replicate the problem with iPhone 6 / iOS 10 device, unfortunately to no avail.
Could you please try it with latest `tns-core-modules`?

**Comment by ignaciolarranaga** [comment]
I detected it was because the tns prepare for some extrange reason was not populating the permissions on the app (i.e. adding them to Info.plist). Will close this in favor of #16
