### ISSUE TITLE
Returning Null Image on iOS

### ISSUE THREAD

**Issue by tuckerjt07** [NativeScript/nativescript-camera#102]
### Which platform(s) does your issue occur on?
iPad  11.2.6

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.1
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): 
"nativescript": {
		"id": "com.walmart.sourcing.flip",
		"tns-android": {
			"version": "3.4.2"
		},
		"tns-ios": {
			"version": "3.4.1"
		}
	},
	"dependencies": {
		"@angular/animations": "~5.2.0",
		"@angular/common": "~5.2.0",
		"@angular/compiler": "~5.2.0",
		"@angular/core": "~5.2.0",
		"@angular/forms": "~5.2.0",
		"@angular/http": "~5.2.0",
		"@angular/platform-browser": "~5.2.0",
		"@angular/platform-browser-dynamic": "~5.2.0",
		"@angular/router": "~5.2.0",
		"@spartadigital/nativescript-permissions": "^1.3.2",
		"angular-2-local-storage": "^1.0.1",
		"angular2-jwt": "^0.2.3",
		"crypto-js": "^3.1.9-1",
		"nativescript-angular": "~5.2.0",
		"nativescript-background-http": "^3.1.0",
		"nativescript-camera": "^3.2.1",
		"nativescript-file-photoview": "^0.1.5",
		"nativescript-floatingactionbutton": "^4.1.3",
		"nativescript-imagepicker": "^4.0.1",
		"nativescript-material-icons": "^1.0.3",
		"nativescript-ng2-fonticon": "^1.3.4",
		"nativescript-photoviewer": "^1.3.0",
		"nativescript-secure-storage": "^2.2.2",
		"nativescript-theme-core": "~1.0.4",
		"nativescript-webview-interface": "^1.4.2",
		"reflect-metadata": "~0.1.8",
		"rxjs": "^5.5.6",
		"sourcing-api-connect-helper": "^2.1.5",
		"tns-core-modules": "^3.4.1",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.6.0",
		"tns-platform-declarations": "^3.4.0",
		"typescript": "~2.6.2"
	}

### Describe the steps to reproduce it.

Open the camera on my device and inspect the returned ImageAsset object. There is no image data, width, height, etc. are all null. Attempting to output to a Base64String also results in a null value.

### Is there any code involved? 
```const _cameraOptions = { keepAspectRatio: true, saveToGallery: false };
    camera.takePicture(_cameraOptions)
      .then((imageAsset: ImageAsset) => {
        if (device.isAndroid) {
          return callbackFunction(imageAsset, token, environment, newSession, this);
        } else {
          const _imageSource = new imageSource.ImageSource();
          return _imageSource.fromAsset(imageAsset).then((result) => {
            console.log("Size: " + imageAsset.options.width + "x" + imageAsset.options.height);
            console.log(result.toBase64String('jpg', 100));
          });```

**Comment by lini** [comment]
I was not able to reproduce the issue in the camera using an iPad running iOS 11.2. I tried using the demo app from this repo and pasted the code you gave in the `main-page.ts` file. The only thing I changed was the `_cameraOptions` parameter and set it to:

```javascript
{ 
  width: 300,
  height: 300,
  keepAspectRatio: true,
  saveToGallery: false
}
```

I got the expected output:

```bash
CONSOLE LOG file:///app/main-page.js:23:28: Size: 300x300
CONSOLE LOG file:///app/main-page.js:24:28: /9j/4AAQSkZJRgABAQAAkACQAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAACQAAAAAQAAAJAAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAligAwAEAAAAAQAAAyAAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/AABEIAyACWAMBEQACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE
```

I suggest you try using the demo app to test and updating to the latest NativeScript version(4.0) if you have not done so already.

**Comment by nsplugins** [comment]
I close this issue due to inactivity.
