### ISSUE TITLE
Convert image to base64

### ISSUE THREAD

**Issue by JijeshP** [NativeScript/nativescript-camera#105]
How can i covert the image to base 64 string after capturing the image

tried the below option but its not working'

`then((imageAsset) => {
      let imageData = imageAsset.toBase64String("jpeg");
      console.log(imageAsset);
    }).catch((err) => {
        console.log("Error -> " + err.message);
    });
  `

**Comment by JijeshP** [comment]
The below code is working for me !

`then((imageAsset) => {
            let source = new ImageSource();
            source.fromAsset(imageAsset).then((source) => {
                const base64image = source.toBase64String("jpg",60);
            });
        }, 
        (err) => {
            console.log("Error -> " + err.message);
        });`

**Comment by salamohamad** [comment]
on iOS device I get an error saying 'Error -> Can\'t find variable: imageSource' 
am I doing something wrong?

**Comment by warlog3** [comment]
I'm facing the same issue @salamohamad

**Comment by rubenassink** [comment]
Anyone fixed it?

**Comment by luishdez87** [comment]
I think i can help you guys @salamohamad , @warlog3 @rubenassink 
import this:
`import * as ImageSourceModule from "tns-core-modules/image-source/";`

and implement this in a method:
`    ImageSourceModule.fromAsset(this.imageSrc).then(image => {
      let base64 = image.toBase64String('png');
      console.log(base64);
    })`

**Comment by luishdez87** [comment]
> on iOS device I get an error saying 'Error -> Can't find variable: imageSource'
> am I doing something wrong?

That Class is on "tns-core-modules/image-source/image-source"

**Comment by MrCalamitus** [comment]
For NativeScript8 I can resolve with this 

````js

import { ImageSource } from '@nativescript/core/'

let convertImageToB64 = async imageAsset => {
  try {
	  const imageSource = await ImageSource.fromAsset(imageAsset)
	  const b64Image = imageSource.toBase64String('jpeg', 50)
	  console.log('b64Image', b64Image)
  } catch (err) {
	  console.trace(err)
  }
}
````


where *imageAsset* is a native image 

I found that *new ImageSource(); source.fromAsset(imageAsset)* was depricated
