### ISSUE TITLE
not asking for permissions next time after  not allowing access

### ISSUE THREAD

**Issue by ghost** [NativeScript/nativescript-camera#106]
it's not asking for permissions next time after the not allowing access to camera and images.

what I want is: if user don't allows it for first time, next time when user taps on take image (for example) to show permissions dialog again.

**Comment by NickIliev** [comment]
@giorgi-abashidze the feature to check for permissions is not part of the nativescript-camera plugin. You could use the [nativescript-permissions](https://github.com/NathanaelA/nativescript-permissions) plugin and its method `hasPermission` to explicitly check if the permissions are given and then implement a logic to ask again when needed.

**Comment by NickIliev** [comment]
@giorgi-abashidze as a side note there is no option in iOS to ask for permission second time - this is a native workflow. All you can do is to redirect the user to the Settings page where he should manually grant the permissions. (explained [here](https://stackoverflow.com/a/29980902/4936697))
