### ISSUE TITLE
Capturing image taking too long in android 7.0

### ISSUE THREAD

**Issue by JijeshP** [NativeScript/nativescript-camera#111]
Which platform(s) does your issue occur on?
- Android
- Version : 7.0 

After capturing image device showing black screen for 10-15 seconds.

**Comment by Jmchemama** [comment]
Hello, I noticed the same problem.

-  Android
-  NativeScript CLI: 4.1.0.

**Comment by JijeshP** [comment]
@Jmchemama its bit faster on Android Oreo but still there is a delay

**Comment by Jmchemama** [comment]
I have test on an s8 and I have more than 10s of black screen. By against a Oneplus6 Oreo I have 5s black screen before returning to the application.
I still find it long.

**Comment by JijeshP** [comment]
@nsndeck @NickIliev what could be the issue here ?

**Comment by NickIliev** [comment]
@JijeshP is there any specific code or is this reproducible with the basic demo?

**Comment by JijeshP** [comment]
@NickIliev No Specific code, it can be reproducible with demo.

**Comment by shamoh19** [comment]
![screenshot_20180611-163042](https://user-images.githubusercontent.com/13183784/41231757-32a19fea-6d95-11e8-8ff3-65ffe3c52fec.png)

Facing same issue with demo project

**Comment by NickIliev** [comment]
@JijeshP @shamoh19 the demo project is creating an `ImageSource` which might cause a delay in some older devices. On another hand, an explicit creation of the image source is not needed in the majority of real-life scenarios (e.g. you could directly bind the image asset).

Try removing the creation of ImageSource and observe if this will resolve your delay issues.
```
// REMOVE THE FOLLOWING CODE

let source = new imageSourceModule.ImageSource();
source.fromAsset(imageAsset).then((source) => {
    let width = source.width;
    let height = source.height;
    if (app.android) {
        // the android dimensions are in device pixels
        width = layout.toDeviceIndependentPixels(width);
        height = layout.toDeviceIndependentPixels(height);
    }

    console.log(`Size: ${width}x${height}`);
});
```

**Comment by JijeshP** [comment]
@NickIliev when i remove the above mentioned code its working fine..
Please find my code below.  

```
let source = new ImageSource();
         source.fromAsset(imageAsset).then((source) => { 
           let base64 = source.toBase64String("png", 60); 
          });
```

How can i achieve this without imageSource.

**Comment by NickIliev** [comment]
@JijeshP you could use native solution to work directly with the native asset (the `ImageAssset` in NativeScript is `android.graphics.Bitmap` on Android and `UIImage` on iOS).

For example, creating base64 from `android.graphics.Bitmap`

```
    requestPermissions().then(
        () => {
            takePicture({ width: 300, height: 300, keepAspectRatio: true, saveToGallery: true }).
                then((imageAsset) => {
                    page.bindingContext.set("cameraImage", imageAsset);

                    imageAsset.getImageAsync((nativeImage) => {
                        console.log(nativeImage); // nativeImage is android.graphics.Bitmap on Andriod and UIImage on iOS

                        if (isAndroid) {
                            let byteArrayOutputStream = new java.io.ByteArrayOutputStream();
                            nativeImage.compress(android.graphics.Bitmap.CompressFormat.PNG, 100, byteArrayOutputStream);
                            let byteArray = byteArrayOutputStream.toByteArray();

                            console.log("ButeArray: ")
                            console.log(byteArray);
                        }
                    });
                }, (err) => {
                    console.log("Error -> " + err.message);
                });
        }, () => {
            alert('permissions rejected')
        });
```

**Comment by shamoh19** [comment]
how can we achieve this in nativescript angular?
