### ISSUE TITLE
Change message when asking for permissions to access Camera

### ISSUE THREAD

**Issue by miguelopezv** [NativeScript/nativescript-camera#118]
I've submitted my app to the App Store and they're asking to change the message that appears the first time you use the camera, and instead display a message that explains why are you requesting access to the camera or what are you going to do with the photo. How can I change this message?

**Comment by NickIliev** [comment]
@miguelopezv try to manually set the message in your project's `info.plist` file

**_app/App_Resources/iOS/Info.plist_**
```
<key>NSCameraUsageDescription</key>
<string>camera description.</string>
```
