### ISSUE TITLE
How to retrieve extra image created by plugin?

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/nativescript-camera#122]
on Android when savetogallery is set to true to get the file path after one takes a picture, you call:
       imageAsset.android
However another image is created also but there is no reference to it in the imageAsset object. Is there a way to get this image? I am trying to get a reference to this image so that I can delete it. In my case it does not have the "NSIMG" prefix. This is the only issue I am having with the camera plugin.

**Comment by NickIliev** [comment]
@leocrawf depending on the device manufacturer the gallery save logic might differ but overall you should look for the **_camera roll_** folder on the device ussually [using this](https://stackoverflow.com/a/16993276/4936697) 

> Note: The saveToGallery option might have unexpected behavior on Android! Some vendor camera apps (e.g. LG) will save all captured images to the gallery regardless of what the value of saveToGallery is. This behavior cannot be controlled by the camera plugin and if you must exclude the captured image from the photo gallery, you will need to get a local storage read/write permission and write custom code to find the gallery location and delete the new image from there.
