### ISSUE TITLE
requestPermissions should be blocking

### ISSUE THREAD

**Issue by zzador** [NativeScript/nativescript-camera#125]
I'm calling "requestPermissions()" right away before I take a picture. However when I take the first picture after I started the developement session, android presents me 2 confirm-dialogs (camera permissions) while in the background my app is already presenting me an error message that I have not the permissions to use the camera. Only at the second try, when the permissions are already given the photo can be captured.

**Comment by lini** [comment]
The `requestPermissions()` method returns a promise. You must wait for the promise to resolve before trying to take a picture. We will update the documentation to better explain this.
