### ISSUE TITLE
No consistent EXIF data stored in pictures on Samsung Galaxy S7

### ISSUE THREAD

**Issue by KavehR** [NativeScript/nativescript-camera#129]
The nativescript-camera plugin won't save any EXIF data in pictures on a Samsung Galaxy S7 whereas the Samsung camera app behaves / save them normally. I am trying with the ^4.0.2 version.

I also tried my app on a Motorola G3, and the metadata are properly written in the picture (??).

Any clue about what's wrong and a possible fix ? (Thanks)

I thought the plugin should expose all the camera functions and preferences as set in the main camera app, but it seems not the case for the Galaxy S7 Edge..

**Comment by DimitarTodorov** [comment]
Hi @KavehR,  
This is a known issue with the android camera interface of all Samsung devices. It seems that their camera app doesn't follow some of the standards. The different manufacturers like LG, Motorola, Samsung etc. have different Camera interfaces. The reason that EXIF data is not obtained by the nativescript-camera plugin is in the Samsung’s camera application. The app is different and although the exif information is requested by the nativescript-camera plugin, it is not returned from the Camera application. The situation is different on other devices like Nexus or Motorola for example - where the exif information is returned from their Camera app and the metadata is properly written.

**Comment by KavehR** [comment]
Hi Dimitar Todorov,
Thank you very much for shedding more light on this issue. 
Since I only needed GPS's lat/long, I worked it out for now, by directly using nativescript's geolocation plugin in order to get those values.
It seems a likely more homogeneous solution across all the targets for the moment (at least in my case).
But thanks again for clarifying.
