### ISSUE TITLE
Properly document requestPermissions

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/nativescript-camera#139]
As the title says - the docs in the readme do not specify that requestPermissions returns a promise. I lost quite a bit of time trying out figure this out. :\ 

And here is an example of someone else also having an issue: https://stackoverflow.com/questions/51190059/camera-capture-function-is-not-working-for-ios

**Comment by lini** [comment]
Apologies for the confusion. The docs will be updated to reflect this.
