### ISSUE TITLE
The plugin does not allow to control where to pick the pictures (camera, library, etc.)

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-camera#14]
I noticed that when I opened the CamaraTest app at the device and the emulator (same OS = iOS 10 / same Phone = IPhone6) it does different things, here are the 2 screenshots, in 1 case it opens the photo library, in the other, it does open the camera app.

In iOS this is because it is switching automatically the UIImagePickerControllerSourceType, no so familiar with the same on Android

Real device:
![real_phone_screenshot](https://cloud.githubusercontent.com/assets/15932965/19618182/77f99e38-9819-11e6-8c1a-34a1cd3a7472.jpg)

Emulator:
![emulator_screenshot](https://cloud.githubusercontent.com/assets/15932965/19618195/b3e016c0-9819-11e6-8346-619a2cca2baa.jpg)

**Comment by nsndeck** [comment]
On iOS simulator this is an expected behavior. The idea is to select an image and test with it. On Android some emulators do have support for camera (either use PC camera or select an image from file system (configured on simulator)).

**Comment by ignaciolarranaga** [comment]
Thanks @nsndeck, any way I raised a pull request to support this on iOS. I think it is a good feature.

The problem is when you want to pick a picture from your library.

In my context for example, I want the user to select some image from his library (it would be the most probable scenario). As the plugin is right now this is impossible, since when the camera opens the access to the library is not available (I think this changed recently), so it is like the only option I'm giving to the user is to take a picture at the moment, which for my scenario is not likely to be a solution.
