### ISSUE TITLE
The first time that i tried to take a picture, it failed in ios and android

### ISSUE THREAD

**Issue by German1293** [NativeScript/nativescript-camera#153]
Versions
nativescript-camera -->>4.1.1
nativescript    
  "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
<img width="281" alt="captura de pantalla 2018-11-30 a la s 12 43 15" src="https://user-images.githubusercontent.com/44504329/49308403-cc558680-f49d-11e8-9713-aeb52cca542a.png">

    
##The problem is that after taking a photo, when you close the camera, the page reloads and even returns you to the previous view, after this when you return to take a photo already works correctly.
Please help.

`function takePicture(args) {
    const page = args.object
   camera.requestPermissions().then(() => {
        const options = { width: 300, height: 300, keepAspectRatio: true, saveToGallery: true };
       camera.takePicture(options)
           .then(imageAsset => {
               if (application.android) {
                   
                  page.bindingContext.set('file', imageAsset.android);

               } else {
                   var source = new imageSource.ImageSource();
                   source.fromAsset(imageAsset).then( function (imageSource) {
                       var folder = fs.knownFolders.documents();
                       var path = fs.path.join(folder.path, "temp" + Date.now() + ".jpg");
                       var saved = imageSource.saveToFile(path, "jpg");
                       console.dir(saved);
                       page.bindingContext.set('file', path);
                   })
               }

           }, err => {
               console.dir(err)
           });

   })
}`

This is the error 
------------------------
System.err: java.lang.RuntimeException: Unable to resume activity {io.checkmap.app/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3506)
System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:110)
System.err: 	at android.os.Looper.loop(Looper.java:203)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
System.err: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:4585)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4426)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4366)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4339)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1007)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
System.err: 	at android.app.BackStackRecord.run(BackStackRecord.java:815)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
System.err: 	at android.app.FragmentController.execPendingActions(FragmentController.java:371)
System.err: 	at android.app.Activity.performResume(Activity.java:6764)
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
System.err: 	... 8 more

**Comment by German1293** [comment]
#

**Comment by lini** [comment]
`The specified child already ...`  exception should be fixed in the latest version of the `tns-core-modules`  (5.0.5 at the moment). Please update your app or test using one of the demo applications in this repository, which already use it.
