### ISSUE TITLE
Error in "index.d.td" for function "requestPermissions"

### ISSUE THREAD

**Issue by lord-saumagen** [NativeScript/nativescript-camera#162]
Dear Ladies and Gentlemen,

it came to my attention that the definition of the "requestPermission" function is erroneous.
The function is implemented as an asynchronous function for android as well as for IOS. See 
the pictures below.

![image](https://user-images.githubusercontent.com/9468599/51244902-850c5200-1986-11e9-8a0a-ced45f9c8fd3.png)

![image](https://user-images.githubusercontent.com/9468599/51244910-8e95ba00-1986-11e9-9ee3-733317a3e0be.png)

The android implementation calls a function which returns a promise. The IOS implementation constructs a promise in the function implementation.

Unfortunately the type definition doesn't show that the function returns a promise. That made me 
believe the function executes synchronously, which lead to some strange behaviors in my program.

![image](https://user-images.githubusercontent.com/9468599/51245184-3c08cd80-1987-11e9-94c6-fd4cd929af1e.png)

It would be very nice if you could update the "index.d.ts" file.

Kind regards, Lord Saumagen.

**Comment by tgpetrov** [comment]
Hi @lord-saumagen,
Thank you for your feedback. The change is made and will be included in the next release of the plugin.
