### ISSUE TITLE
Put mediaTypes as an option

### ISSUE THREAD

**Issue by developper89** [NativeScript/nativescript-camera#18]
Hi, I had some trouble removing the video option in the camera view 
what i did was to set the mediatypes array to 
`imagePickerController.mediaTypes = [mediaTypes[0]];`
It would be better to pass the type as an option like `"public.image" or "public.movie"` 
and choose between them to enable or disable the photo or video option in the view 
Could you add the mediaTypes array as an option or make it settable  ?

**Comment by nsndeck** [comment]
Hi @developper89,

We will add such functionality once we are ready to support it. We have plans to improve this plugin to support also video. Unfortunately I cannot commit with an exact time frame when this will be ready, but we will work on it soon.

**Comment by fsciuti** [comment]
Hello...news about this fix? :)

**Comment by valentinstoychev** [comment]
It is scheduled for our next release - 2.5.0 - https://github.com/NativeScript/NativeScript/issues/3241

**Comment by fsciuti** [comment]
Thanks!!!! :)

**Comment by maddy2get** [comment]
Hello, any progress on this yet? Really waiting for this to the my app to release.

**Comment by davecoffin** [comment]
was this added in 2.5.0?

**Comment by b-hobbs** [comment]
+1

**Comment by davecoffin** [comment]
@valentinstoychev @nsndeck This being the recommended camera implementation for nativescript core, I really think it needs some attention. I would imagine a lot of apps are using it (2,336 downloads in the last month), and there are some basic issues in this repo that havent been addressed for months, including this one. Can we get an update?

**Comment by Cayan** [comment]
+1

**Comment by adamauckland** [comment]
Hi, this issue seems to be a year old and untouched. Can I just raise a PR to implement removing the "video" option? It doesn't really make sense to show the "video" option when `camera.takePicture()` returns an image asset.

**Comment by DimitarTachev** [comment]
I'm closing this issue because it has been inactive for a few months.

**Comment by DimitarTachev** [comment]
Hi guys,

Sorry for the long silence and thanks for your contribution! The takePicture method will set only the image media type out of the box in the next plugin version.

The fix is part of pull request #62 and should be available in NPM until the end of the week as the plugin is in a process of becoming a verified one.

As part of this process, the plugin will also follow the recommended plugins structure shown in the [plugins seed](https://github.com/NativeScript/nativescript-plugin-seed) which will make the community contributions a lot of easier!

**Comment by adamauckland** [comment]
Thanks for the great work, DimitarTachev!

**Comment by zbranzov** [comment]
The fix should be already published to NPM. Enjoy!
