### ISSUE TITLE
Add allowsEditing flag for iOS

### ISSUE THREAD

**Issue by msaravitz** [NativeScript/nativescript-camera#180]
Add the allowsEditing flag for iOS. The allowsEditing flag is helpful for ensuring the image is square (this also lets them choose which part of the photo is in the square) and allows the user to "zoom in/crop" even after the photo has been taken. 

Current: 
![nativescript-camera](https://user-images.githubusercontent.com/16619557/54784126-7433c300-4bf9-11e9-974f-d4d13a0a04fb.png)

With allowsEditing:
![ios allows editing](https://user-images.githubusercontent.com/16619557/54784141-7b5ad100-4bf9-11e9-8ba2-5d295e62278b.png)

**Comment by DimitarTodorov** [comment]
Hi, @msaravitz 
The feature is now available in nativescript-camera@4.4.0, which is published in npm.
