### ISSUE TITLE
can you guys add face detection to this ?

### ISSUE THREAD

**Issue by Davidzhu001** [NativeScript/nativescript-camera#187]
can you guys add face detection to the camera function like expo or react native?

**Comment by NickIliev** [comment]
@Davidzhu001 this would require MLKit which is beyond the simple camera functionalities. However the plugin nativescript-plugin-firebase is coming with MLKit functionality and this said there is already a face detection implementation - see [here](https://twitter.com/eddyverbruggen/status/994627242524332032?lang=bg)

**Comment by Davidzhu001** [comment]
@NickIliev thanks so muh.
