### ISSUE TITLE
Version update issue: ReferenceError: androidx is not defined

### ISSUE THREAD

**Issue by ghost** [NativeScript/nativescript-camera#190]
After version update of nativescript-camera ^4.3.0 to ^4.4.0, I am getting runtime error like below:
Can someone please fix it?

`Project successfully built.
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
TNS.Native: NativeScript Runtime Version 5.1.0, commit 4497f43b69cb57ce65ece2aac5b98b2010f857
TNS.Native: JNI_ONLoad
TNS.Native: JNI_ONLoad END
TNS.Native: V8 version 6.9.427.23
TNS.Native: lenNodes=95904, lenNames=955965, lenValues=1240934
TNS.Native: time=0
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error calling module function
System.err:
System.err: ReferenceError: androidx is not defined`

**Comment by elena-p** [comment]
Hi @ruchitaecor,

Could you try to delete your node_modules and platforms folders and build again? 
I checked the demo projects in the repo with both 5.1.0 and 5.3.0 android runtimes and everything works fine. 
The androidx error could be connected with the latest version of nativescript-permissions plugin (which is a dependency of the camera plugin) and not connected to updating nativescript-camera from 4.3.0 to 4.4.0. 
If the error persists, could you send us a demo project that we could use to track down the cause?

**Comment by ghost** [comment]
@elena-p 

Thanks for the reply. I removed node_modules, platforms, and hooks almost 7 to 8 times to find the issue in my existing project. Yes, you are right it related to nativescript-permissions plugin which is a dependency of nativescript-camera plugin. This I found in error log after much deep concentration. Then I just revert nativescript-camera plugin to version 4.3.0 again and everything working correctly.
