### ISSUE TITLE
application.currentContext is deprecated

### ISSUE THREAD

**Issue by Huc91** [NativeScript/nativescript-camera#193]
- Android versions 
- device: Nexus 5x

- CLI: 5.3.4
- Cross-platform modules: 5.3.1
- Runtime(s): 5.0.0
- Plugin: "nativescript-camera": "^4.4.0",

Run a new project with the nativescript-camera plugin, returns in console:

```
application.currentContext is deprecated; use startActivity, foregroundActivity, or context instead
```
The plugin works, but since deprecated stuff tends to be removed some day, it would be cool to fix this in the future

**Comment by zbranzov** [comment]
Released in version 4.4.1.
