### ISSUE TITLE
ios takepicture twice errors

### ISSUE THREAD

**Issue by narayananl23** [NativeScript/nativescript-camera#22]
When takepicture is called for the second time, it errors. 

Error happens only in iPhone 6 10.2, works fine in android. 

My environment 

> "nativescript-camera": "0.0.8",
> Component        │ Current version │ Latest version │ Information      │
> │ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date       │
> │ tns-core-modules │ 2.4.2           │ 2.4.3          │ Update available │
> │ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date       │
> │ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date
> 

My code
```
viewModel.camOnTap = function () {
        console.log("inside camOntap");
        cameraModule.requestPermissions();
        //console.log(cameraModule.isAvailable());
        var options = { width: 100, height: 100, keepAspectRatio: true };
        //var curImageData ="" ;
        cameraModule.takePicture().then(imageAsset => {
            console.log("Result is an image asset instance"+imageAsset);
            viewModel.set("myImage", imageAsset);
            imageSource.fromAsset(imageAsset).then(res => {
                console.log(res.toBase64String(enums.ImageFormat.png));
                viewModel.imageData = res.toBase64String(enums.ImageFormat.png);
            })
        }).catch(function (err) {
            console.log("Error -> " + err.message);
        });
    }
```

Error
```
1   0x10bc53f6b NativeScript::FFICallback<NativeScript::ObjCBlockCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10c3ed90e ffi_closure_unix64_inner
3   0x10c3ee2c2 ffi_closure_unix64
4   0x110a57808 _dispatch_call_block_and_release
5   0x110a7912e _dispatch_client_callout
6   0x110a5f1f8 _dispatch_queue_override_invoke
7   0x110a609dc _dispatch_root_queue_drain
8   0x110a60782 _dispatch_worker_thread3
9   0x110e55712 _pthread_wqthread
10  0x110e551ed start_wqthread
file:///app/tns_modules/nativescript-camera/nativescript-camera.js:88:19: JS ERROR TypeError: undefined is not an object (evaluating 'imageAs
Dec 17 18:01:29 geetha-mba com.apple.CoreSimulator.SimDevice.E9EAFE5B-0707-4233-B499-23407321CB4C.launchd_sim[3026] (UIKitApplication:com.tra
ation.nativescript[0xb4de][27270]): Service exited due to Segmentation fault: 11
```

**Comment by narayananl23** [comment]
It can be closed or needs a fix. but found the issue because The demo works fine :)

My code was missing options, once I added options no issues.

from
 `cameraModule.takePicture().then(imageAsset => {`
to 
` cameraModule.takePicture(options).then(imageAsset => {`

**Comment by tsonevn** [comment]
Hi @narayananl23, 

I tested the given case with the [example ](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) with options and without options, however was unable to reproduce such an issue. It could be something related with the project. If you have further problem with the camera plugin, you could open a new one.

Regards,
@tsonevn
