### ISSUE TITLE
The app crashes periodically

### ISSUE THREAD

**Issue by PashaArkus** [NativeScript/nativescript-camera#221]
### Which platform(s) does your issue occur on?
- Android
- 7.1.2, 6.0.1, 9.1
-  What type of device? device

### Please, provide the following version numbers that your issue occurs with:

- CLI:6.1.0
- Cross-platform modules: 6.1.0
- Runtime(s): "tns-android": {
      "version": "6.1.0"
    }
- Plugin(s): "dependencies": {
    "nativescript-camera": "^4.5.0",
    "nativescript-google-maps-sdk": "^2.7.0",
    "nativescript-permissions": "^1.3.7",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-sidedrawer": "~7.0.0",
    "nativescript-vue": "~2.4.0",
    "nativescript-windowed-modal": "^6.0.0",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.1.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.2.0",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
The application periodically crashes after I take photos. This happens most often on Xiaomi (redmi 3s, redmi 4x) and Nokia (6.1) phones. When you return from the camera, the application restarts itself and writes the following errors in the device’s console:

ActivityManager: Process org.nativescript.TestCameraApp (pid 8370) has died: prev LA
or
ActivityManager: Process ua.com.getmancar (pid 615) has died: prev S

I also want to note that such a problem does not always appear, it happens after the first photo, it happens after 7, and sometimes after 20.
As a test method, I noticed that these errors appear if you use the plugin "nativescript-google-maps-sdk

### Is there any code involved? 
[TestCameraApp.zip](https://github.com/NativeScript/nativescript-camera/files/3589235/TestCameraApp.zip)

**Comment by PashaArkus** [comment]
Is this issue being addressed?

**Comment by elena-p** [comment]
Hi @PashaArkus,

It seems that these errors are caused by the `nativescript-google-maps-sdk` plugin - https://github.com/dapriett/nativescript-google-maps-sdk/issues/206. You could try the workaround provided by @shiv19 - https://shiv19.com/how-to-fix-nativescript-google-maps-sdk-map-view-crash-inside-scroll-view/

**Comment by PashaArkus** [comment]
Hi. Unfortunately your decision did not help me

**Comment by PashaArkus** [comment]
This [video](https://drive.google.com/file/d/18KupocmBGixBCse6XkI-7mt9idAZH6ga/view) shows how the application works
