### ISSUE TITLE
 No v4 support

### ISSUE THREAD

**Issue by edrick27** [NativeScript/nativescript-camera#226]
I am using nativescript v6, and   "nativescript-camera": "^4.1.1". when i try to use camera console show  No v4 support. the code is: 

requestPermissions().then( () => {
                takePicture({ width: 300, height: 300, keepAspectRatio: true, saveToGallery: this.saveToGallery })  .then((imageAsset: any) => {
                        this.SavePictures(imageAsset);
                    }, (error) => { });
 }, () => alert('permissions rejected')

**Comment by xsterlas** [comment]
@aaayushsingh - "add the latest nativescript-permissions lib to your project and import it anywhere. This will fix the issue"
This solution from other issue works perfectly: [https://github.com/NativeScript/nativescript-geolocation/issues/246](https://github.com/NativeScript/nativescript-geolocation/issues/246)
