### ISSUE TITLE
Camera takePicture hangs after using nativescript-imagepicker, w/ saveToGallery: true

### ISSUE THREAD

**Issue by kinggolf** [NativeScript/nativescript-camera#23]
Using nativescript-camera and [nativescript-imagepicker](https://github.com/NativeScript/nativescript-imagepicker) in same app, so maybe this issue should be posted to imagepicker module(??). Both modules work independent of each other, however, under specific conditions the camera module seems to hang with no error message, testing so far only on iOS & using NG2.

Hanging condition sequence -
1) Use imagepicker module to access camera roll, select a single image, then use this image in the app.
2) Use camera module to take a photo with option saveToGallery:true. The new photo is saved to gallery, but it seems there is no promise returned and no error thrown.

From either picker or camera, the app adds imageSource to an ObservableArray for display and base64 encodes and posts to server.

If I 1st use the camera, it works properly, then use the imagepicker which OK as well. However, the camera module will no longer work afterwards, per above hanging sequence.

If I set saveToGallery:false, then both modules work in any order, the image is just not save to camera roll.

Here is my 'tns info' & image picker/camera modules from package.json:
```
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date  │
│ tns-core-modules │ 2.4.4           │ 2.4.4          │ Up to date  │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date  │

    "nativescript-camera": "0.0.8",
    "nativescript-imagepicker": "^2.4.1",
```

App code using camera module takePicture:
```
    takePhoto() {
        this.drawer.toggleDrawerState();
        console.log("In takePhoto");

        // takePicture imported from "nativescript-camera"
        takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true,
            saveToGallery: false
        }).
            then((imageAsset) => {
                // When app hangs this code is not processed
                let image = new Image();
                image.src = imageAsset;
                console.log("In camera.takePicture, imageAsset.nativeImage = ");
                console.log(imageAsset.nativeImage);

                let imageAsBase64 = fromNativeSource(imageAsset.nativeImage).toBase64String("jpeg");
                this.imagesArray.unshift( { 'imgsrc':fromNativeSource(imageAsset.nativeImage), 'index':this.imagesArrayIndex } );
                this.imagesArrayIndex++;
                this.reindexImagesArray();

                this.addCaptionAndSaveToServer( imageAsBase64 );

            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }
```

App code using imagepicker module"
```
    addExistingPhoto() {
        let context = imagepickerModule.create({
            mode: "single"
        });
        // this.selectedPhotoImgSrc = new ImageSource();
        this.drawer.toggleDrawerState();
        this.startSelection(context);
    }

    startSelection( context ) {
        context
            .authorize()
            .then(() => {
                //this.selectedPhotoArray = [];
                return context.present();
            })
            .then((selection) => {
                selection.map( selected => {
                    selected.getImage().then( v => {
                        // this.selectedPhotoImgSrc = v;
                        console.log( "In startSelection, v = " + v );
                        this.imagesArray.unshift( { 'imgsrc':v , 'index':this.imagesArrayIndex } );
                        this.imagesArrayIndex++;
                        this.reindexImagesArray();
                        let imageAsBase64 = v.toBase64String("jpeg");
                        this.addCaptionAndSaveToServer( imageAsBase64 );
                    });

                });
                // this.selectedPhotoArray = selection;
                // this._changeDetectionRef.detectChanges();
            })
            .catch(function (e) {
                console.log(e);
            });
    }
```

Appreciate any assistance or suggestions.

**Comment by tsonevn** [comment]
Hi @kinggolf,

I reviewed your scenario and created sample project. However I was unable to reproduce this case. I tested it on iOS simulator and real device. 
You could review the sample project [here](https://github.com/tsonevn/NGImagePickerCamera). 
It would help if you could give us some more info about the problem and to send us sample project, where the problem could be debugged locally.

I look forward to hearing from you.
Regards,
@tsonevn

**Comment by kinggolf** [comment]
Thank you @tsonevn, I appreciate your time and response.
I cloned the sample project you provided and I confirm that works as expected.
Then I updated to my project's latest package.json & the app still worked as expected.
```
"dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.4.1",
    "nativescript-angular": "1.2.0",
    "nativescript-camera": "0.0.8",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.4"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.0.10",
    "zone.js": "~0.7.4"
  }
```

I made these following changes to be more similar to my own app:
app.component.html:
```
<StackLayout class="p-20">
    <Button text="Select image" (tap)="onTap()"></Button>
    <Button text="Take picture" (tap)="takePhoto()"></Button>
    
    <GridLayout >
        <!-- <Image id="imageid" width="150" height="150""></Image> -->
        <Image id="imageid" width="150" height="150" [src]="imgsrc"></Image>
    </GridLayout>
</StackLayout>
```

app.component.ts (updates surrounded by **, tried to make bold...):
```
import { Component } from "@angular/core";
var imagepickerModule = require("nativescript-imagepicker");
import {takePicture} from "nativescript-camera";
var fs = require('file-system');
import {Page} from "ui/page";
import {Image} from "ui/image";
import {ObservableArray} from "data/observable-array";
**import { ImageSource, fromNativeSource } from "image-source";**

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public imagesArray:ObservableArray<any>;
    public counter = 0;
    public uploadTask;
    **public imgsrc: ImageSource;**
    constructor(private page:Page){
        this.imagesArray=new ObservableArray();
        **this.imgsrc = new ImageSource();**
    }

    onTap(){
        this.addExistingPhoto();
    }

    addExistingPhoto() {
        let context = imagepickerModule.create({
            mode: "single"
        });
        this.startSelection(context);
    }

    startSelection( context ) {
        var that = this;
        context
            .authorize()
            .then(() => {
                return context.present();
            })
            .then((selection) => {
                selection.map( selected => {
                    console.log("selected map");
                    console.log(selection);
                    selected.getImage().then( v => {
                        **// var image:Image = <Image>this.page.getViewById("imageid");
                        // image.src = v;
                        this.imgsrc = v;**
                        console.log( "In startSelection, v = " + v );
                        console.dump(v);
                    });

                });
            })
            .catch(function (e) {
                console.log(e);
            });
    }

     takePhoto() {
        console.log("In takePhoto");
        takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true,
            saveToGallery: true
        }).
            then((imageAsset) => {
                **this.imgsrc = fromNativeSource(imageAsset.nativeImage);
                // var image:Image = <Image>this.page.getViewById("imageid");**
                console.log("In camera.takePicture, imageAsset.nativeImage = ");
                console.dump(imageAsset);
                **// image.src=imageAsset;**

            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }

    
}
```

When I 'tns run ios' to my phone:
1) Take Picture and the new pic displays but does not save to camera roll
2) Select Image which displays properly
3) Take Picture, the new pic does not display but save to camera roll!
Repeat steps 2 & 3

I am guessing #1 above does not save to camera roll because permission has not been granted which happens in #2. However, I do not understand why the new pic displays in #1, but not in #2.
Any suggestions? 
Thanks again for your support - Larry King

**Comment by tsonevn** [comment]
Hi @kinggolf, 

I was able to reproduce the problem with displaying the image on the screen and setting the new `ImageSource`, while binding the src property of the `Image`.  However I am still unable to reproduce the problem with image saving. I tested the problem on device with `iOS 9.3` and Simulator with `iOS 10`. Could you provide some more info about the device, which you are using for testing.

About the first problem, in the meantime,  you could get the component by `id` and to set the new image source manually as it has been shown below.

```
     takePhoto() {
         var that =this;
        console.log("In takePhoto");
        takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true,
            saveToGallery: true
        }).
            then((imageAsset) => {
                var image:Image = <Image>this.page.getViewById("imageid");
                image.src=imageAsset;
            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }
```

Hope this helps.

**Comment by kinggolf** [comment]
Hi @tsonevn,
I am testing on an iPhone6S, iOS 10.2.

In my actual application, I am adding either the taken photo from camera or selected photo from camera roll to an ObservableArray of Image-Source objects, i.e. I am not displaying a single image, but rather a collection of images via RadListView, so displaying a single image by 'getViewById' is not an option. Additionally, I am converting the selected or taken image to Base64 encoding and saving to the application server. You can see the component code in the original post, above.

Thanks again & cheers - Larry King

**Comment by tsonevn** [comment]
Hi @kinggolf,
In the meantime as a temporary solution, while we are researching the problem with data binding,  you could try to refresh the ListView just after you receive the ImageAsset for  new taken photo. You could review the below-given example.

app.component.html

```
<StackLayout class="p-20">
    <Button text="Select image" (tap)="onTap()"></Button>
    <Button text="Take picture" (tap)="takePhoto()"></Button>
    
    <GridLayout >
        <ListView id="listviewid" [items]="imagesArray" class="list-group">
            <template let-item="item" let-odd="odd" let-even="even">
              <StackLayout>
                <Image [src]="item.imgsource"></Image>
              </StackLayout>
            </template>
        </ListView>
    </GridLayout>
    
</StackLayout>
```

app.component.ts

```
import { Component } from "@angular/core";
var imagepickerModule = require("nativescript-imagepicker");
import {takePicture} from "nativescript-camera";
var fs = require('file-system');
import {Page} from "ui/page";
import {Image} from "ui/image";
import {ObservableArray} from "data/observable-array";
import { ImageSource, fromNativeSource } from "image-source";
import {ListView} from "ui/list-view";


@Component({
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    public imagesArray:ObservableArray<any>;
    public counter = 0;
    public uploadTask;
    public imgsrc: ImageSource;
    constructor(private page:Page){
        this.imagesArray=new ObservableArray();
        this.imgsrc = new ImageSource();
    }

    onTap(){
        this.addExistingPhoto();
    }

    addExistingPhoto() {
        let context = imagepickerModule.create({
            mode: "single"
        });
        this.startSelection(context);
    }

    startSelection( context ) {
        var that = this;
        context
            .authorize()
            .then(() => {
                return context.present();
            })
            .then((selection) => {
                selection.map( selected => {
                    console.log("selected map");
                    console.log(selection);
                    selected.getImage().then( v => {
                        console.log( "In startSelection, v = " + v );
                        console.dump(v);
                        this.imagesArray.push({imgsource:v});
                    });

                });
            })
            .catch(function (e) {
                console.log(e);
            });
    }

     takePhoto() {
         var that =this;
        console.log("In takePhoto");
        takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true,
            saveToGallery: true
        }).
            then((imageAsset) => {
              
                this.imagesArray.push({imgsource:imageAsset});
                setTimeout(()=>{
                    var listview:ListView =<ListView> this.page.getViewById("listviewid");
                    listview.refresh();
                }, 1000)
                
                

            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }

    
}
```

**Comment by tsonevn** [comment]
Hi @kinggolf, 

We research this problem and found that the problem has been related with the time the image has been pushed to the array. In your case the image has been pushed before it has been loaded in the memory and this is causing the problem.

The solution for this scenario is to use `getImageAsync` ImageAsset method, which will return native Image, when the picture has been loaded, which you could add to the array. 

I am also attaching sample code.

```
takePhoto() {
         var that =this;
        console.log("In takePhoto");
        takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true,
            saveToGallery: true
        }).
            then((imageAsset) => {

                imageAsset.getImageAsync((image) => {
                    this.imagesArray.push({imgsource:image});
                })

                
                

            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }
```

Let me know whether this helps.

**Comment by kinggolf** [comment]
@tsonevn Yes, this works! Thank you very much!!
I had been trying to understand how/where to use image-asset in iOS, and this helps make sense of it.
BTW - there is a "console.log" statement in nativescript-imagepicker.
CONSOLE LOG file:///app/tns_modules/nativescript-imagepicker/images.js:19:20: 667
I am wondering why this continues to appear even after the image-picker selection has been completed and while taking a new photo? Does this make sense?

<img width="764" alt="ngimagepickercamera" src="https://cloud.githubusercontent.com/assets/9776423/21918880/b97cbcbe-d90a-11e6-98d9-48bbfa5f8681.png">


Thanks again for the help.

**Comment by kinggolf** [comment]
@tsonevn I have also been trying to figure out a way to use Angular's @ViewChild rather than 
```
                        let listview:ListView =<ListView> this.page.getViewById("listview1");
                        listview.refresh();
```
Any advice here? Thx.

**Comment by tsonevn** [comment]
Hi @kinggolf ,
About your first comment. I verify the `console.log("In takePhoto")` and it seems that this message has been print in the console only when I start taking new image. Regarding to that, could you verify, whether this issue is not related with your code and the time you are taking the image.

For the other question, I am providing example how to access the element, while using  `ViewChild` instead of `this.page.getViewById("listview1");`

app.component.html

```
<StackLayout class="p-20">
    <Button text="Select image" (tap)="onTap()"></Button>
    <Button text="Take picture" (tap)="takePhoto()"></Button>
    
    <GridLayout >
        <ListView #lvlistview id="listviewid" [items]="imagesArray" class="list-group">
            <template let-item="item" let-odd="odd" let-even="even">
              <StackLayout>
                <Image [src]="item.imgsource"></Image>
              </StackLayout>
            </template>
        </ListView>
    </GridLayout>
    
</StackLayout>
```

app.component.ts

```
import { Component, ViewChild, ElementRef } from "@angular/core";
........


@Component({
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    public imagesArray:ObservableArray<any>;
    public counter = 0;
    public uploadTask;
    public imgsrc: ImageSource;


    @ViewChild("lvlistview") mylistViewRef: ElementRef;

......

     takePhoto() {
         console.log(this.mylistViewRef.nativeElement);
         ..........
    }

    
}
```

Hope this helps.

**Comment by kinggolf** [comment]
Thanks again @tsonevn.  I previously tried your exact solution with the exception of using RadListView not ListView and this did not work. When I inserted ListView directive for RadListView it worked as you suggest. I experimented more today and researched and came across this [Github issue](https://github.com/NativeScript/nativescript-angular/issues/188), that got me thinking about using RadListViewComponent rather than ElementRef, as such:
`
    @ViewChild("radlistview1") radListView1: RadListViewComponent;
`
And using listView property on RadListViewComponent:
`
            this.radListView1.listView.refresh();
`
Then success!!

Also, concerning my other question - I apologize for not being clear. Yes, `console.log("In takePhoto");` is in my code. But what I was asking is why the console.logmessage from inside imagepicker module continues executing even when I am not selecting an image from the camera roll?
`
CONSOLE LOG file:///app/tns_modules/nativescript-imagepicker/images.js:18:20: 667
`
I only highlighted ` console.log("In takePhoto");` above to illustrate I was taking a photo and not using the image-picker, but you can see the imagepicker CONSOLE LOG messages continue. Any ideas?
Thanks again.

**Comment by tsonevn** [comment]
Hi @kinggolf,

I reviewed the problem with the `console.log` and found that this problem has been related with the global `orientationChanged` event, which has been used for checking the device orientation.

We register this event on first start of `nativescript-imagepicker`. I also notice that we have missed to remove to `console.log`s, which prints the current height and width of the screen.

I will remove [those console.log s](https://github.com/NativeScript/nativescript-imagepicker/blob/master/nativescript-imagepicker/images.ios.ts#L23-L24) and this should be available in next release of `nativescript-imagepicker`.

PR [63](https://github.com/NativeScript/nativescript-imagepicker/pull/63)

Regards,
@tsonevn

**Comment by kinggolf** [comment]
@tsonevn 
Good deal.
Thanks again for all your help.
Best - Larry King
