### ISSUE TITLE
Camera not working with Android 10 and singleInstance Launch mode

### ISSUE THREAD

**Issue by flodaniel** [NativeScript/nativescript-camera#236]
### Which platform(s) does your issue occur on?
- Android 10

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2
- Cross-platform modules: 6.2

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Open the camera and take a picture. 
The plugin will return the error "cancelled"
This only happens on Android 10 with singleInstanceMode.
Everything else works fine.

**Comment by anthonywebster** [comment]
i have the same problem :(

**Comment by anthonywebster** [comment]
i foud this answer:  it seems like the one I didn't test was the one most obvious to test: saveToGallery: false.

const options: CameraOptions = {
      width: this.imageSize,
      height: this.imageSize,
      cameraFacing: 'front',
      allowsEditing: true,
      keepAspectRatio: true,
      saveToGallery: false // <-- this did the trick
    };

**Comment by AdamAtri** [comment]
pull request for fix: https://github.com/NativeScript/nativescript-camera/pull/237/commits/dc4b9ebb5729f17eb3c687120df36f34b86b702f
