### ISSUE TITLE
App crashes when saving photo on Android 10 devices

### ISSUE THREAD

**Issue by jakubgondar** [NativeScript/nativescript-camera#245]
### Which platform(s) does your issue occur on?
Android 10 (Android 9 and lower seems to work fine), devices that I have tested this issue: 
- Samsung Galaxy M20 (SM-M205FN, Kernel: 4.4.177-17406009)
- Android 10 emulator (Pixel_3_API_29_Android_10_with_Play_Store)

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): `"tns-android"`: 6.5.0
- Plugin(s): "nativescript-camera": 4.5.0
- Dependencies:
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "nativescript-angular": "~8.21.0",
    "nativescript-camera": "~4.5.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.5.1",
    "typescript": "~3.5.3"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Nativescript-camera plugin does not work on Android 10 devices, our clients were complaining mostly about Samsung Galaxy and Xiaomi MI devices. It does not work also on Android 10.

### Is there any code involved? 
I am attaching simple demo app that is supposed to just take photo and show it in Angular component. App was generated via command `tns create` as Angular Hello world app.
[tns650.zip](https://github.com/NativeScript/nativescript-camera/files/4735749/tns650.zip)

To reproduce issue:
1) unpack ZIP
2) run `npm ci` (installs exact vesions from package-lock.json
3) run `tns platform clean android`
4) run `tns debug android`
5) Click "Click here to take photo", allow permissions and take photo. After taking photo, photo should appear below the button on screen.

On Android 10 emulator, it throws error `JS: Error: cancelled` in the console.
On Samsung Galaxy M20, application crashes. See attached GIF video how it behaves on real device:
![ezgif com-resize](https://user-images.githubusercontent.com/3504491/83874207-694d4b80-a735-11ea-83fa-6e315dc0c06d.gif)

Error stack:
[tns650error.txt](https://github.com/NativeScript/nativescript-camera/files/4735916/tns650error.txt)

### Workaround
I have found out that when targetSdkVersion is set to 28 (not default 29 in TNS 6.5.0) then application works :
```
...
android {
	defaultConfig {
		minSdkVersion 17
		targetSdkVersion 28
...
```

**Comment by aschurf** [comment]
I get a similar error in Xiaomi Mi9se on Android 10 QKQ, after the photo the application closes

**Comment by octo888** [comment]
Same on Pixel 3a and Samsung S20 (both android 10)

**Comment by Geotracer** [comment]
I have the same issue with my recent app. 
Even with the same type of phone, the app crashes when confirming the photo.
Mostly after the first install, the app crashes.
The other times it crashes randomly.

**Comment by akshaysisodia** [comment]
I also have the same issue in my redmi k20 image didn't appears and in console it shows JS:  Error: cancelled.

**Comment by NathanaelA** [comment]
You need to add the following key `android:requestLegacyExternalStorage="true"` if you are targetting API 29 or higher and you want to use the normal file api.
```
<manifest ... >
<!-- This attribute is "false" by default on apps targeting
     Android 10 or higher. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

**Comment by jakubgondar** [comment]
@NathanaelA thanks for response, but would you mind at least adding this note to the plugin home page README.md? TNS 6.5.0 has default target API 29 so apps built with this plugin **will by default crash** on Android 10.

**Comment by akshaysisodia** [comment]
@NathanaelA Thank You So much it worked

**Comment by BMwanza** [comment]
@NathanaelA's solution did not work for me.

My target API is set to 29, as it is now required by the Play Store, but I cannot get it work. App crashes when trying to take a picture
