### ISSUE TITLE
camera take pickture not stored on phone

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-camera#25]
_From @Leo-lay on January 18, 2017 6:42_

Hi, i use the camera plugin and take pickture,and set the options **saveToGallery:true**  but i don't see the photo in the album.

ios:10.0.2(14A456)
nativescript:2.4.0

follow is my code 

```
onTakePhoto() {
        let options = {
            width: 600,
            height: 800,
            keepAspectRatio: false,
            saveToGallery: true
        };
        camera.takePicture(options).then(
            imageAsset => {
                console.log('imageAsset takePicture=>', imageAsset);
                // let source = imageSource.fromAsset(imageAsset);
                // this.saveFile(source);
                // this.makeImageFile(imageAsset);
                this.imageTaken = imageAsset;
                this.photoList.push(this.imageTaken);
                console.log('Size: ' + imageAsset.options.width + 'x' + imageAsset.options.height);
                // this.selections.push(imageAsset);
                console.log('imageAsset=>', JSON.stringify(imageAsset));
                this.photoList.forEach((item) => {
                    console.log('this.photoList=>', JSON.stringify(item));
                    console.log('length', this.photoList.length);
                });

            }).catch(error => {
                console.log('take photo error=>', error.message);
            });
    }
```

_Copied from original issue: NativeScript/NativeScript#3504_

**Comment by tsonevn** [comment]
Hi @Leo-lay,

I have tested `nativescript-camera` plugin with [this ](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) sample project on `iOS` and it seems to work as expected. 
Could you verify, whether you will have the same problem, while using the sample project [here](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest).
It will help if you could provide sample project, which could be debugged locally.

Regards,
@tsonevn

**Comment by Leo-lay** [comment]
Hi @tsonevn ,
i push a demo[ here](https://github.com/Leo-lay/camerasample.git), also don't see on phone gallery,but it's show in my demo.
and another question: how can i get the path of pickture ? because i want upload to server.

Thanks & Regards.

**Comment by tsonevn** [comment]
Hi @Leo-lay, 
I reviewed your project and found that the problem has been related due to missing permissions to access the phone gallery.
To be able to fix this behavior you should first call `nativescript-camera` plugin `requestPermissions();` method, which will ask the user for the needed permissions and you will be able to save the images in the gallery.

About your second question you should first save the image on some temporary file and then to take file path. For further help, you could review the sample code [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L93-L106).

Hope this helps.
