### ISSUE TITLE
Camera not opening on android 11

### ISSUE THREAD

**Issue by AnthonyLenglet** [NativeScript/nativescript-camera#252]
### Which platform(s) does your issue occur on?
- Android 
- 11
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.8
- Cross-platform modules: 6.5.20
- Runtime(s): tns-android: 6.5.1
- Plugin(s):
```
    "@nativescript/theme": "2.3.3",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-app-sync": "^2.0.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.1",
	// local copy of https://github.com/NativeScript/nativescript-datetimepicker/pull/76
    "nativescript-datetimepicker": "file:../nativescript-datetimepicker/publish/package/nativescript-datetimepicker-1.2.2.tgz",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-material-bottomnavigationbar": "^3.1.7",
    "nativescript-phone": "^1.4.0",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-sentry": "^1.9.1",
    "nativescript-unit-test-runner": "^0.7.0",
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Whenever we try to take a picture, the camera never pops up, and no error is given in the console

### Is there any code involved? 
```ts
    try {
      await requestPermissions();
      const imageAsset = await takePicture({
        width: 100,
        height: 100,
        allowsEditing: true,
        keepAspectRatio: true,
      });
      return imageAsset;
    } catch (err) {
      this.alertRefusedPermissions({
        title: "Accès à l'appareil photo refusé",
        message:
          "l'accès à l'appareil photo a été refusé, veuillez l'activer via la page paramètres afin de l'utiliser",
      });
      throw 'Permissions refused';
    }
```

**Comment by jcassidyav** [comment]
I am seeing the same thing, it does not work  for me unless I use nativescript@6.7.4 to build anything higher and I see this behavior.

**Comment by jcassidyav** [comment]
For me it was down to tarketSDK, newer cli defaulting it to 30, changing it to 29 in settings.json and it now works.

**Comment by kourtzaridisr88** [comment]
Same issue here

**Comment by DanielDent** [comment]
I believe the issue is that the plugin is currently only compatible with API level 28. At API level 29, adding `android:requestLegacyExternalStorage="true"` to the app manifest is available as a workaround, but this option is no longer available at API level 30.

**Comment by IhaveQs** [comment]
I am experiencing the same problem. 

Phone: Google Pixel (3a &4XL)
Android version: 11
tns-android: 6.5.3
nativescript/core: 6.5.12
nativescript-camera: 4.5.0
 
This problem did not exist with Android 10 or with any other brand of phone (only Google Phones)
 
 - The suggestion to set the targetSDK to 28 or 29 did not help. 
 - android:requestLegacyExternalStorage="true" is already part of out AndroidManistest.
 - I also don't understand the following suggestion "nativescript@6.7.4" -> there is no nativescript/core version 6.7.4!
 
 Trial and error has determined the problem to be the following condition: 
 " if (takePictureIntent.resolveActivity(utils.ad.getApplicationContext().getPackageManager()) != null) " 
 -> found in /node_modules/nativescript-camer/camera.android.js
 -> If the condition is deleted, then the camera opens!

 I would very much appreciate suggestions on how to reactive the camera function, without forking the project and deleting the condition.
 
 Thank you for your help!

**Comment by itsmerockingagain** [comment]
Hi All, Can anyone provide a solution for this issue in android 11? seems like NS is not supporting latest OS android 11 on NS6

**Comment by AdrianoOP** [comment]
Same thing here... Any update?

**Comment by vicmasa** [comment]
Same thing here... Any update?

**Comment by AnthonyLenglet** [comment]
I haven't personally touched the project in a bit, but we're not getting any issues on our end anymore since having updated everything to `"@nativescript/camera": "^5.0.6"` and `"@nativescript/core": "~8.1.1"`

since this no longer seems to be a problem on the newer version, I will close this issue
