### ISSUE TITLE
tns run android fails to build after adding the plugin.

### ISSUE THREAD

**Issue by halaharr** [NativeScript/nativescript-camera#27]
I keep getting the following error after adding the plugin. If I remove the plugin it works fine.  Can you please let me know if there are any more dependencies that I need to install
```
	C:\A2ZMobile\devmain\A2Z.FieldCompass\A2Z.FieldCompass\A2Z.FieldCompass\platforms\android\src\F0\AndroidManifest.xml:48:4-72 Error:
	Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.A2ZFieldServices.FieldCompass.provider) from AndroidManifest.xml:48:4-72
	is also present at AndroidManifest.xml:48:4-72 value=(com.A2ZFieldServices.FieldCompass.fileprovider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:4:3-12:14 to override.

```

**Comment by tsonevn** [comment]
Hi @halaharr,

After adding the plugin with `tns plugin add nativescript-camera`, delete `platforms` folder clear npm cache with `npm cache clear`. 

Then try again to rebuild the project with `tns run android`

Hope this helps

**Comment by DimitarTachev** [comment]
I'm closing this issue because it has been inactive for a few months.
