### ISSUE TITLE
module fails on NS2.1.6 Samsung Gs7, it doesn`t fire onActivityResult

### ISSUE THREAD

**Issue by AlexPak** [NativeScript/nativescript-camera#28]
I believe it would work if do the following:
1.  Add:  var _activity = appModule.android.foregroundActivity || appModule.android.startActivity;
1.1. Substitute: appModule.android.onActivityResult = (requestCode: number, resultCode: number, data: android.content.Intent) => {
onto 
_activity.onActivityResult = (requestCode: number, resultCode: number, data: android.content.Intent) => {
1.2 Substitute: 
appModule.android.foregroundActivity.startActivityForResult(takePictureIntent, REQUEST_IMAGE_CAPTURE);
onto

_activity.startActivityForResult(takePictureIntent, REQUEST_IMAGE_CAPTURE);

**Comment by AlexPak** [comment]
By the way this is the events trail:

JS: Event: activityPaused, Activity: com.tns.NativeScriptActivity@6d69864
JS: Event: saveActivityState, Activity: com.tns.NativeScriptActivity@6d69864
JS: Event: activityStopped, Activity: com.tns.NativeScriptActivity@6d69864
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@6d69864
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:1047)
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:1028)
03-05 13:55:30.837  2330  2330 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@6d69864

**Comment by DimitarTachev** [comment]
Hi @AlexPak

Sorry for the long silence and thanks for the suggested workaround.

Unfortunately, the minimum NativeScript version required by the plugin is 3.0.0. I suggest you update your project to the latest NativeScript version and open a new issue if the issue is still reproducible.

Other possible solution could be using a custom fork of the repo with the above-mentioned workaround if updating NativeScript is not applicable for you.
