### ISSUE TITLE
Saving image to file system

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-camera#3]
I'm having problems saving the image taken with the camera to the file system.

The following test works. I'm able to create an imageSource from a local resource and save it to the file system:

``` javascript

var cameraModule = require("nativescript-camera");
var fs = require('file-system');
var imageSource = require("image-source");


var img = imageSource.fromResource("some_resource_that_exists");

var folder = fs.knownFolders.documents();
console.log('folder - ', folder); // => object

var path = fs.path.join(folder.path, "Test.png");
console.log('path - ', path); // => correct path

var saved = img.saveToFile(path, "png");
console.log('saved - ', saved); // => true

var imgLocal = imageSource.fromFile(path);

// ### binding to "imgLocal" works. Image is displayed
pageData.camera.set("cameraImage", imgLocal);
```

Yet doing the same thing with the image returned from the camera plugin fails silently at `saveToFile()`:

``` javascript
var cameraModule = require("nativescript-camera");
var fs = require('file-system');
var imageSource = require("image-source");


cameraModule.takePicture({
    width: 300,
    height: 300,
    keepAspectRatio: true
}).then(function (imageAsset) {
    console.log("Image taken!");

    var img = imageAsset;

    var folder = fs.knownFolders.documents();
    console.log('folder - ', folder); // => object

    var path = fs.path.join(folder.path, "Test.png");
    console.log('path - ', path); // => correct path

    var saved = img.saveToFile(path, "png"); // ### Execution stops here.
    console.log('saved - ', saved);

    var imgLocal = imageSource.fromFile(path);

    pageData.camera.set("cameraImage", img);
});
```

Am I doing something incorrectly?

```
┌──────────────────┬───────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version       │ Latest version │ Information │
│ nativescript     │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.4.0-2016-10-07-4335 │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.3.0                 │ 2.3.0          │ Up to date  │
└──────────────────┴───────────────────────┴────────────────┴─────────────┘
```

**Comment by NickIliev** [comment]
Hey @3rror404 

This issue appears to be reproducible when testing on iOS simulator but the camera module works as expected in real device. We are working on a fix for the simulator and will update the info [here](https://github.com/NativeScript/NativeScript/issues/2871)..

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/2871#issuecomment-252599280](https://github.com/NativeScript/NativeScript/issues/2871#issuecomment-252599280)

**Comment by xanZ08** [comment]
I put the saveToFile in a try catch block, and I get the below error 
JS: TypeError: img.saveToFile is not a function
I am running TNS 3.0.1
This issue is same, on my emulator, as well as on my device - Nexus 4 - android 5

**Comment by xanZ08** [comment]
Would really appreciate some help. I need this thing working to move ahead .

**Comment by lautaroramos** [comment]
Hi @3rror404  I think I have the solution for your problem. 
In your code snippet, You are trying to call the .saveToFile() method in the imageAsset returned by the camera, but if you check the API reference you will see that imageAsset doesn't have that method.

For doing what you want to do you have to convert the imageAsset to an imageSource, calling the static method .fromAsset() from the image-source module, which returns a promise with an imageSource. 

From there you can call the .saveToFile() method in the imageSource that you converted from the imageAsset. Here's a example:

```

var imageSourceModule = require("image-source");
var camera = require("nativescript-camera");
var fs = require("tns-core-modules/file-system");

exports.onLoaded = function onLoaded(args) {
    camera.requestPermissions();
    camera.takePicture()
        .then(imageAsset => {
            let documents = fs.knownFolders.documents();
            let path = fs.path.join(documents.path, "pic.png");
            imageSourceModule.fromAsset(imageAsset)
                .then(imageSource => {
                     imageSource.saveToFile(path, "png");
                 });
        });
}

//For the sake of simplicity I omitted the catch blocks
```

I hope I helped.

**Comment by peni4142** [comment]
I have nearly the same Problem.

my code: 

`import { Component, OnInit, ElementRef, ViewChild } from "@angular/core";
import { Image } from "ui/image";
import * as camera from "nativescript-camera";
import * as fs from "tns-core-modules/file-system"
import * as imageScoure from "tns-core-modules/image-source";

import { ImageAsset } from "tns-core-modules/image-asset/image-asset";




@Component({
    selector: "camera",
    moduleId: module.id,
    templateUrl: "./camera.html",
})
export class Camera implements OnInit {
    @ViewChild("img") image : ElementRef;

    aImageAsset: ImageAsset;

    takePicture(){
        camera.requestPermissions();
        
            let theImage: Image = this.image.nativeElement;
            console.log("get image ready")
            console.log("smile!")
            camera.takePicture()
            .then((imageAsset) => {
                theImage.src = imageAsset;
                this.aImageAsset = imageAsset;
            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }

    save(){
        console.log("execute save")        
        if(this.aImageAsset){
            let documents = fs.knownFolders.documents();
            let path = fs.path.join(documents.path, "AppPic.png");
            imageScoure.fromAsset(this.aImageAsset).then(imageScoure =>{
                imageScoure.saveToFile(path, "png");
                console.log("imageSource.saveToFile");
            });            
        }else{
            console.log("No Asset");
        }
    }


    constructor() { }

    ngOnInit(): void {
        
    }
}`
camera.html:
`<FlexboxLayout flexDirection="column" class="page">
    <Image #img src="https://www.google.com/images/errors/logo_sm_2.png" > </Image>
    <Button text="smile!" (tap)="takePicture()"> </Button>
    <Button text="save" (tap)="save()"> </Button>
</FlexboxLayout>`

Can someone tell me why I don't find the Image anywhere on my (emulated) device?
