### ISSUE TITLE
imageAsset is undefined

### ISSUE THREAD

**Issue by vswee** [NativeScript/nativescript-camera#31]
on iOS 10 and android 4.0+ both real devices I cannot get any data returned from imageAsset after takePicture. It simply always returns undefined which makes it impossible to save the file to the app filesystem or to work further on the image to convert to base64 etc.

Here's an error from a simple binding example: 

CONSOLE LOG file:///app/views/e/ason/ason.js:102:20: Error -> undefined is not an object (evaluating 'page.bindingContext = ({imageSrc: imageAsset})')

All the errors generally match that format - all feature the undefined issue

**Comment by tsonevn** [comment]
Hi @vswee,
Thank you for interest in NativeScript,
I reviewed your case, however, was unable to reproduce this behavior, while using  [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) app. 
The `imageAsset` has been returned as expected on both iOS and Android.

Could you verify the sample project on your side and to verify, whether you will have the same problem?
It would also help if you could share some code with us.
