### ISSUE TITLE
[Android] App back to splash screen when the camera returns

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-camera#36]
_From @dzfweb on March 27, 2017 13:38_

I have an app with nativescript + angular that closes when i call camera's api, returning to splash screen.. I think it's because of the low memory of the dispositive, because only occur on old devices. Is there a way to force the app still open on first stage, even when opening other app (in my case, camera) ?

_Copied from original issue: NativeScript/NativeScript#3879_

**Comment by tsonevn** [comment]
Hi @dzfweb, 
I tested your case while using [CameraTestAngular](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTestAngular) plugin, however, was unable to reproduce the same behavior.
Regarding that could you provide some further info, about the device or emulator API Level? Could you also provide some sample project, which could be debugged locally?

**Comment by tsonevn** [comment]
_From @dzfweb on March 27, 2017 15:41_

For reproduce the scenario, i used android 4.4.4, open some android apps on the dispositive, and then back to the app and open the camera. When the camera returns, in some case android close the app and it will open again from the begin (splash screen).

is there a way to use the camera without close the app, to evict it scenario, or other solution?

**Comment by tsonevn** [comment]
Hi @dzfweb,
I tested this case on a device with Android 4.4.4, however, was unable to reproduce this behavior on my side. I am using [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) app for testing.
You could review the steps that I follow:
1. deploy `CameraTest` app on the device with `tns run android`.
2. open another android app on the device.
3. return back to the NativeSciprt app and open the camera by tapping on `Take Picture` button.
4. take a new picture and we will be returned to the app, without restarting the whole application.

It would help if you could provide sample project and steps, which could help us to debug this scenario.

**Comment by tsonevn** [comment]
_From @dzfweb on March 29, 2017 16:4_

I understand you, the fact only occurs on Samsung J1, and is not ever, just sometimes.
I have it problem in other project developed in Xamarin, and i solved by reducing the quality of the camera photo, and it sizes, but i 'm not getting in NativeScript 'cause other bug (https://github.com/NativeScript/nativescript-camera/issues/35)

**Comment by tsonevn** [comment]
Hi @dzfweb,
Let's move this issue in the `nativescript-camera` repository and keep the discussion there. 
Regarding the issue [#35](https://github.com/NativeScript/nativescript-camera/issues/35). The reported problem seems to affect only the save option on some Android device. You should be able to change the sizes of the image(width and height).

Could you try to setup image size in takePicture method and to verify, whether this resolve the issue with app restart. For Example:
`takePicture({width: 100, height: 100, keepAspectRatio: false, saveToGallery: saveToGallery})`

**Comment by dzfweb** [comment]
@tsonevn picture resizes not workint properly too. The size of the image after the taken was the same of the original.

**Comment by tsonevn** [comment]
Hi @dzfweb,
This problem with image size is related to the imageSource module and its fromAsset method, which will create a source always with the same dimensions. In this case, you could use the imageAsset from the newly taken image

You could also verify this case on your side while using [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) app and replacing the code for `onTakePictureTap` method with the below attached one.
```
export function onTakePictureTap(args: EventData) {
    let page = <Page>(<View>args.object).page;
    let saveToGallery = page.bindingContext.get("saveToGallery");
    takePicture({width: 900, height: 900, keepAspectRatio: false, saveToGallery: saveToGallery}).
        then((imageAsset:ImageAsset) => {
            let source = new imageSourceModule.ImageSource();
            console.log("image assest")
            console.dump(imageAsset.options)
            imageAsset.getImageAsync((image)=>{
                console.log(image)
            })
            imageSourceModule.fromAsset(imageAsset).then((source) => {
                console.log(`Size: ${source.width}x${source.height}`);
            });
            page.bindingContext.set("cameraImage", imageAsset);
        }, 
        (err) => {
            console.log("Error -> " + err.message);
        });
}
```

When you take a new picture, you will see that the imageAsset will be with the correct dimensions, while respecting the setup options in `takePicture` method.
About the imageSource problem, I logged new issue [here](https://github.com/NativeScript/NativeScript/issues/3955).

**Comment by SBD580** [comment]
@tsonevn This is not working either. `getImageAsync` returning image in the wrong size (you can check `image.getWidth()` on android to verify.
The only workaround I have found was to use `imageAsset.android` which hold the path for the full size image and then load it from there.
