### ISSUE TITLE
takePicture method not returning promise in Android (but does in iOS)

### ISSUE THREAD

**Issue by wired4code** [NativeScript/nativescript-camera#38]
Running the test-camera example (nativescript-camera/examples/CameraTest/app/), everything works just fine in iOS and the image (selected from the gallery) is displayed on the screen. But when I test this same code running the Android emulator, after the camera opens and I snap a photo and click on save, the photo does not display on the screen. So I tested by adding a console.log right after the promise should return to see what I'm getting back:
```
takePicture({width: 180, height: 180, keepAspectRatio: false, saveToGallery: saveToGallery}).
        then((imageAsset) => {
            console.log("IMAGE ASSET", imageAsset);
            let source = new imageSourceModule.ImageSource();
            source.fromAsset(imageAsset).then((source) => {
                console.log(`Size: ${source.width}x${source.height}`);
            });
            page.bindingContext.set("cameraImage", imageAsset);
        }, 
        (err) => {
            console.log("Error -> " + err.message);
        });
```
The IMAGE ASSET console log never shows in terminal, I mean nothing. Not even the string I passed, and there are no errors.  The console.log does show in terminal when I run the app in the iOS simulator, but in Android nothing. I'm using the Android Studio virtual device (a Nexus 5X running Android 7.1). 

I tried to search online to see if others have run into this issue. Couldn't find anything.

**Comment by wired4code** [comment]
Update: a friend tested on his Android device, and it's working fine. I may have misunderstood how the dummy camera in emulator is supposed to work. He explained that after snapping a photo, it should give me the option to select that photo or take another, but because it doesn't, that's likely why the promise is not returning. Can someone confirm?

**Comment by wired4code** [comment]
Update: the example using Angular works just fine on Android emulator and on device. It's the non-Angular example that's not working.

**Comment by tsonevn** [comment]
Hi @wired4code,
Thank you for contacting us. I reviewed this case on my side while using [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) sample app. However, everything seems to work as expected while building the app on emulator and real device. 

Regarding that, could you verify, whether you have the correct permissions `WRITE_EXTERNAL_STORAGE` and `CAMERA` in `AndroidManifest.xml` file, which are needed for the plugin to work properly? 

Meanwhile, you could also verify, whether you will have the same problem, with API level lower than 24. It would also help if you could also provide some more info about the emulator.

**Comment by briosheje** [comment]
@tsonevn 
I'm expecierncing this issue in Android 8.0.0 on a Nexus 5x.

Relevant code:

```
if (isAndroid) {
      if (!permissions.hasPermission(android.Manifest.permission.CAMERA)) {
        permissions.requestPermission(android.Manifest.permission.CAMERA).then((ok) => {
          if (!permissions.hasPermission(android.Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            permissions.requestPermission(android.Manifest.permission.WRITE_EXTERNAL_STORAGE).then((ok2) => {
              this.pickAndSavePicture();
            });
          }
        },
        (awrrr) => {
          
        });
      }
}

public pickAndSavePicture() {
    console.log("taking picture!");
    camera.takePicture()
    .then((imageAsset) => {
        console.log("Result is an image asset instance");
        let imgName = "test";
        let imgFormat = "png";

        this.filesystem.writeImageFile(imageAsset, this.filesystem.mkdir("OS4U"), imgName, imgFormat);
    }).catch((err) => {
        console.log("Error -> " + err.message);
    });
  }
```

The .then callback is called only at the FIRST execution of the application: from the second execution onwards the callback never gets called, I get the console.log above ("Taking picture"), then no errors or anything appears, I just get this on the console:

`JS: >>> onActivityResult 1: 3453`

Using latest version of nativescript (3.3) and latest version of tns-core-modules.
