### ISSUE TITLE
Camera doesn't open from a modal view

### ISSUE THREAD

**Issue by Jai-Krish** [NativeScript/nativescript-camera#41]
Here is a minimal project for testing
[ModalCamera.zip](https://github.com/NativeScript/nativescript-camera/files/1029161/ModalCamera.zip)

**Comment by tsonevn** [comment]
Hi @Jai-Krish,
Thank you for the attached sample project, I reviewed the problem, however, this behavior is something expected and at this time navigating to another Page from Modal Page is not supported. The same scenario is while using `nativescript-camera` plugin.

We have already logged a [feature request](https://github.com/NativeScript/NativeScript/issues/3753) about this case and you could keep track on it for further info.
In the meantime, you could close the modal page before opening the camera.

**Comment by netowp** [comment]
NativeScript 4.1 already supports modal navigation. Should this issue be opened again?

**Comment by tsonevn** [comment]
HI @netowp,
Can you provide more info about your case and the issue, which you are facing? It will help if you send us sample project, where the problem can be e reproduced. If there is a real issue with the modal page and the camera plugin, we can reopen it.
