### ISSUE TITLE
Custom Camera View

### ISSUE THREAD

**Issue by ghost** [NativeScript/nativescript-camera#44]
Hello Friends,

i never used github to post a issue in the past so i hope i do it right.

This is not a issue, its more like a question how to solve a problem.

I only want to know if the following is possible with native script.

1.) Count taken pictures and do a custom action (upload all taken pictures) after picture x
2.)  Overlay the camera with a layer, place a indicator on the layer  so that users can see how many pictures left until action will be executed.

I hope you understand what want. If not please ask.

Sorry for my english.

**Comment by NickIliev** [comment]
@bErNd1986 yes, you can achieve all that with NativeScript. using the MVVM pattern you can create your view-model and provide a counter variable to "watch" for the number of taken photos and based on that counter to execute your logic for upload (there is a dedicated plugin for background-upload called nativescript-background-upload).

Howev3er, the issue system is not for how-to related questions and providing custom solutions but more for discussing features, bugs, and issues with the product. Pease direct your question in one of the community channels lie [discourse.nativescript.org](https://discourse.nativescript.org/) or SO
