### ISSUE TITLE
Set image path

### ISSUE THREAD

**Issue by Clifte** [NativeScript/nativescript-camera#49]
I looked into code and verified the image path is generated based on timestamp is it possible to give an path to image file?

**Comment by tsonevn** [comment]
Hi @Clifte,
Could you provide more info about the problem, which you are facing and how you are getting the path of the newly created image? 

It would also help if you could provide a sample project, which could be debugged locally.

**Comment by Clifte** [comment]
I'd like to set or get the path where the image is stored.
something like this:

note the filePath property:
 ```
takePicture({width: 180, height: 180, keepAspectRatio: false, filePath:"./IMAGEFILE.jpg"}).
        then((imageAsset) => {
            let source = new imageSourceModule.ImageSource();
...
...

```

**Comment by tsonevn** [comment]
Hi @Clifte,
In this case, you could use `saveToFile` method provided from the `imageSource` modules. For further help, you could review the sample code in this project, where the same technic is used for the image picker.
