### ISSUE TITLE
Cannot find image-asset module

### ISSUE THREAD

**Issue by ShawnPavel** [NativeScript/nativescript-camera#5]
I'm attempting to test this on an Android device with NativeScript Angular. I get the following error: 

```
 node_modules/nativescript-camera/nativescript-camera.d.ts(1,29): error TS2307: Cannot find module 'image-asset'.
```

I installed the plugin using the `tns plugin install nativescript-camera` as described in the [src\README.md](https://github.com/NativeScript/nativescript-camera/blob/master/src/README.md).
I didn't see in the example project where this module was included. Is `image-assset` perhaps not part of Nativescript Angular? 

Below is some information about my app.

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐                                                                                           
│ Component        │ Current version │ Latest version │ Information │                                                                                           
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date  │                                                                                           
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date  │                                                                                           
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date  │                                                                                           
│ tns-ios          │ 2.3.0           │ 2.3.0          │ Up to date  │                                                                                           
└──────────────────┴─────────────────┴────────────────┴─────────────┘      
Dependencies:                                                                                                                                                   
┌───────────────────────────────────┬───────────────┐                                                                                                           
│ Plugin                            │ Version       │                                                                                                           
│ @angular/common                   │ 2.0.0         │                                                                                                           
│ @angular/compiler                 │ 2.0.0         │                                                                                                           
│ @angular/core                     │ 2.0.0         │                                                                                                           
│ @angular/forms                    │ 2.0.0         │                                                                                                           
│ @angular/http                     │ 2.0.0         │                                                                                                           
│ @angular/platform-browser         │ 2.0.0         │                                                                                                           
│ @angular/platform-browser-dynamic │ 2.0.0         │                                                                                                           
│ @angular/platform-server          │ 2.0.0         │                                                                                                           
│ @angular/router                   │ 3.0.0         │                                                                                                           
│ email-validator                   │ ^1.0.4        │                                                                                                           
│ moment                            │ ^2.15.1       │                                                                                                           
│ nativescript-angular              │ ^1.0.1        │                                                                                                           
│ nativescript-camera               │ 0.0.3         │                                                                                                           
│ nativescript-geolocation          │ 0.0.13        │                                                                                                           
│ nativescript-mapbox               │ ^1.5.0        │                                                                                                           
│ nativescript-plugin-firebase      │ ^3.7.1        │                                                                                                           
│ nativescript-ripple               │ ^1.0.1        │                                                                                                           
│ nativescript-telerik-ui           │ ^1.4.1        │                                                                                                           
│ reflect-metadata                  │ ^0.1.5        │                                                                                                           
│ rxjs                              │ 5.0.0-beta.12 │                                                                                                           
│ tns-core-modules                  │ ^2.3.0        │                                                                                                           
└───────────────────────────────────┴───────────────┘                                                                                                           
Dev Dependencies:                                                                                                                                               
┌─────────────────────────────┬─────────┐                                                                                                                       
│ Plugin                      │ Version │                                                                                                                       
│ babel-traverse              │ ^6.13.0 │                                                                                                                       
│ babel-types                 │ ^6.13.0 │                                                                                                                       
│ babylon                     │ ^6.9.0  │                                                                                                                       
│ codelyzer                   │ 0.0.28  │                                                                                                                       
│ lazy                        │ 1.0.11  │                                                                                                                       
│ nativescript-dev-typescript │ ^0.3.2  │                                                                                                                       
│ tslint                      │ ^3.15.1 │                                                                                                                       
│ typescript                  │ 2.0.3   │                                                                                                                       
│ zone.js                     │ ^0.6.21 │                                                                                                                       
└─────────────────────────────┴─────────┘
```

**Comment by ShawnPavel** [comment]
I figured it out! After removing the node_modules, and platforms I did a `tns init`, `tns install` and voila.

**Comment by mariano-aguero** [comment]
I run the sample that exists in the repo, and currently still having the same problem.
Apply the fix suggested by @ShawnPavel but the problem still exist

**Comment by Tashfa** [comment]
I just started working on nativescript with javascript and i couldn't find much tutorials. I tried everything but my application is not accessing my device camera. Please help me out.

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.CameraTest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

ReferenceError: imageAsset is not defined
File: "file:///data/data/org.nativescript.CameraTest/files/app/main-page.js, line: 13, column: 14

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/main-page.js', line: 13, column: 15
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


ReferenceError: imageAsset is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/main-page.js', line: 13, column: 15
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

ReferenceError: imageAsset is not defined
File: "file:///data/data/org.nativescript.CameraTest/files/app/main-page.js, line: 13, column: 14

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/main-page.js', line: 13, column: 15
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


ReferenceError: imageAsset is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/main-page.js', line: 13, column: 15
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
	Frame: function:'', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.CameraTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6955)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
	... 9 more
