### ISSUE TITLE
Upload to s3 without save the photo

### ISSUE THREAD

**Issue by bzaruk** [NativeScript/nativescript-camera#53]
There is a way to take a picture with the camera module ("nativescript-camera") without saving into the storage?
I just want to uplaod it to s3 - For now I am saving it and upload the saved file into s3
so now I need to figure out how to not save it and upload the image from the app memory
I can actually save it - upload it - and remove it...But is there a better way to do that?

**Comment by tsonevn** [comment]
Hi @shabib3,
You could use the imageSource  for the newly created image and to use `toBase64String` method to get the image as a base64 string, which could be uploaded to the service. Then you will be able to upload the image, without the need to save it temporarily.  For example:
```
takePicture({width: 180, height: 180, keepAspectRatio: false, saveToGallery: saveToGallery}).
        then((imageAsset) => {
            let source = new imageSourceModule.ImageSource();
            source.fromAsset(imageAsset).then((source) => {
                console.log(`Size: ${source.width}x${source.height}`);
                console.log("image source");
                console.log(source);
                console.log("source to base64");
                console.log(source.toBase64String("png"));
            });
            page.bindingContext.set("cameraImage", imageAsset);
        }, 
        (err) => {
            console.log("Error -> " + err.message);
        });
```

**Comment by bzaruk** [comment]
@tsonevn Awesome I will try it!
