### ISSUE TITLE
(Android) Crash when using back button to close the dialog and then open it again and take a picture

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/nativescript-camera#63]
Hello,
I've just double checked in slack and forum and this problem is reproducible, here the details:

https://discourse.nativescript.org/t/problems-with-nativesckipt-camera-plugin/3006/4

Basically if after I clicked the back button to close the screen I re-execute the code to open it again, and take the picture and confirm, I get the error:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3453, result=-1, data=Intent {  }} to activity {com.anygofitness.anygopartner/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onActivityResult failed

Error: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.anygofitness.anygopartner/files/NSIMG_20171101_173244.jpg (No such file or directory)
    java.io.FileInputStream.open(Native Method)
    java.io.FileInputStream.<init>(FileInputStream.java:146)
    java.io.FileInputStream.<init>(FileInputStream.java:99)
    android.media.ExifInterface.<init>(ExifInterface.java:1106)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Run
```

This is a very important issue, please let me know if you need any other info...

Thanks,
Dem

**Comment by shiv19** [comment]
I confirm @demetrio812 's issue. I was able to reproduce the same using the latest version of the plugin.

**Comment by shiv19** [comment]
@demetrio812 This issue has been resolved in v3.1.3

**Comment by shiv19** [comment]
@DimitarTachev This issue still exists in 3.1.3
Attaching logs
[log.txt](https://github.com/NativeScript/nativescript-camera/files/1444394/log.txt)

**Comment by shiv19** [comment]
@demetrio812 
nativescript-camera@3.1.4 solves this issue. This issue can now be closed :)

**Comment by demetrio812** [comment]
Thanks @shiv19 !
