### ISSUE TITLE
(Android) Back button modal closing event

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/nativescript-camera#64]
Hello,
when open the camera view and then click the back button to close it, I don't have any even to know that I've closed the view, is there a way to know when this happens?

Thanks,
Dem

**Comment by shiv19** [comment]
https://github.com/NativeScript/nativescript-camera/pull/65 @demetrio812 
When this PR is merged,
This issue will be resolved 😄

**Comment by shiv19** [comment]
@demetrio812 Please try v3.1.3,
this issue has been resolved

**Comment by shiv19** [comment]
@demetrio812 nativescript-camera@3.1.4 solves this issue. This issue can now be closed :)

It includes handling back button for iOS

**Comment by demetrio812** [comment]
Thanks!

**Comment by bhavincb** [comment]
how to check if camera is closed using android back button?
