### ISSUE TITLE
v3.1.3 Doesn't have the latest code changes on npmjs

### ISSUE THREAD

**Issue by shiv19** [NativeScript/nativescript-camera#68]
For v3.1.3 release, the code changes which were made, like handling the back button press,
fixing crash after canceling taking an image and trying to capture again, are not a part of v3.1.3 release. The js which is there in that package still contains old code.

**Comment by zbranzov** [comment]
Hi @shiv19,
The changes from your pull request were merged after the release of 3.1.3. As of now, you can enjoy the latest bits in v3.1.4.

**Comment by shiv19** [comment]
@zbranzov thank you so much ^_^
Cheers!
