### ISSUE TITLE
get image path when saveToGallery is true

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-camera#93]
i want to get the image path when image is taken using `saveToGallery:true`.
i need to upload image taken with the camera but i'm unable to get the image path.
i had checked demo and previous issues but didn't get any solutions.

**Comment by zbranzov** [comment]
Hi @bhavincb 
Following the code from the plugin's demo, you can obtain the image path using the imageAsset.android on Android.
```
 then((imageAsset) => {
                    page.bindingContext.set("cameraImage", imageAsset);
                    console.log("src: " + imageAsset.android);
```
On iOS you can save an image from the asset to accessible folder and then use it to upload as shown in [https://docs.nativescript.org/cookbook/image-source#save-image-from-image-asset-to-png-file](https://docs.nativescript.org/cookbook/image-source#save-image-from-image-asset-to-png-file).

You can also use the [nativescript-imagepicker](https://github.com/NativeScript/nativescript-imagepicker) plugin to select the files you want to upload.

**Comment by bhavincb** [comment]
hii @zbranzov ,
thank you for detailed response. it's work as expected.

this information should be provided inside the plugin's README.md .
