### ISSUE TITLE
Android build is crashing after last update

### ISSUE THREAD

**Issue by bachras** [NativeScript/nativescript-camera#95]
Thank you for brilliant plugin. Unfortunately after last update android app build is crashing, nativescript and android is up to date. Here is the error I get :

```
+ add include.gradle from /Users/Art/testApp/node_modules/nativescript-camera/platforms/android/include.gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Art/testApp/platforms/android/app/build.gradle' line: 381

* What went wrong:
A problem occurred evaluating project ':app'.
> String index out of range: -1 
```
Any help/advise is appreciated. Thanks

**Comment by nuno-morais** [comment]
+1

**Comment by lini** [comment]
Thank you for reporting this issue. Version 4.0.1 included a compatibility change for the next version of NativeScript (a bit prematurely). The change has been reverted and version 4.0.2 is published in NPM. There are no other changes so versions 4.0.0 and 4.0.2 are functionally identical.
